version: '3.8' # Versi 3 atau lebih

services:
  item-app:
    image: ghcr.io/ziddma/a433-microservices/item-app:v1
    ports:
      - '80:8080'
    depends_on:
      - item-db
    restart: always # Restart policy
    environment:
      DB_HOST: item-db
      DB_NAME: item-app-db
      NODE_ENV: production

  item-db:
    image: mongo:3
    volumes:
      - app-db:/data/db
    restart: always # Restart policy

volumes:
  app-db: #  Volume untuk menyimpan data MongoDB
